#!/usr/bin/env python3

PORT = 7000

auth_keys = {}

from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import parse_qs
import json

class S(BaseHTTPRequestHandler):
    def _set_auth(self, endpoint):
        self.send_response(302)
        self.send_header('Location', endpoint)
        self.end_headers()

    def _set_unauth(self):
        self.send_response(403)
        self.end_headers()

    def do_GET(self):
        self._set_unauth()

    def do_POST(self):
        post_data = parse_qs(self.rfile.read(int(self.headers['Content-Length'])).decode('utf-8'))
        if 'name' in post_data and post_data['name'][0] in auth_keys:
          self._set_auth(auth_keys[post_data['name'][0]])
        else:
          self._set_unauth()

def run(server_class=HTTPServer, handler_class=S):
    server_address = ('', PORT)
    httpd = server_class(server_address, handler_class)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()

if __name__ == '__main__':
    with open('auth.json', 'r') as jsonfile:
        auth_keys = json.load(jsonfile)
    print("Loaded %d keys." % len(auth_keys)) 
    run()
